### ISSUE TITLE
Can't Seem To Login

### ISSUE THREAD

**Issue by ptiseo-mcs** [iggy-rs/iggy-web-ui#16]
I would love to try to use Iggy-Web, but I can't seem to login. I get to the initial login page but I get a 403 upon clicking the login button and POSTing to http://127.0.0.1:3050/auth/sign-in. Suggestions?

Here's my (partial) docker-compose.yml:

```
  iggy:
    image: iggyrs/iggy:0.4.112
    container_name: pupr-iggy
    environment: # see https://docs.iggy.rs/server/configuration
      IGGY_ROOT_USERNAME: "${PUPR_IGGY_ADMIN}"
      IGGY_ROOT_PASSWORD: "${PUPR_IGGY_ADMIN_PWD}"
      IGGY_HTTP_ENABLED: true
      IGGY_QUIC_ENABLED: true
      IGGY_TCP_ENABLED: true
      IGGY_HEARTBEAT_ENABLED: true
      IGGY_HEARTBEAT_INTERVAL: "5s"
      IGGY_TLS_KEY_PATH: "/etc/iggy/certs/iggy.key"
      IGGY_TLS_CERT_PATH: "/etc/iggy/certs/iggy.crt"
    ports:
      - "3000:3000" # HTTP
      - "8080:8080" # QUIC
      - "8090:8090" # TCP
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8090/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - iggy_data:/var/lib/iggy
      - ./iggy.key:/etc/iggy/certs/iggy.key:ro
      - ./iggy.crt:/etc/iggy/certs/iggy.crt:ro
    networks:
      - pupr
    depends_on:
      - vault

  iggy-web:
    image: iggyrs/iggy-web-ui:latest
    container_name: pupr-iggy-web
    environment:
      PUBLIC_IGGY_API_URL: "http://127.0.0.1:3000"
    ports:
      - "3050:3050" # web ui access
    networks:
      - pupr
    depends_on:
      - iggy
```

![Image](https://github.com/user-attachments/assets/221035ba-21f8-467f-9eaf-a6891300cd04)
